#!/usr/bin/env python3
# -*- coding: utf-8 -*-

' a test module '  # 文档注释

__author__ = 'xi' # 作者

import sys  # 导入模块
sys.path.append('自定义模块路径')

def test():
    args = sys.argv # 获取程序运行的参数列表
    if len(args)==1:
        print('Hello, world!')
    elif len(args)==2:
        print('Hello, %s!' % args[1])
    else:

if __name__=='__main__': # 本模块的测试
    test()